services:
  - type: web
    name: serva-api
    env: node
    plan: free
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/v1/bookings
